# -*- mode: ruby -*-
# vi: set ft=ruby :
current_dir = File.dirname(File.expand_path(__FILE__))
server_ip = "192.168.42.110"

server_worker_ip = "192.168.42.111"

server_script = <<-SHELL
	sudo -i
	export INSTALL_K3S_EXEC="--bind-address=#{server_ip} --node-external-ip=#{server_ip} --flannel-iface=eth1 --write-kubeconfig-mode=644"
	curl https://releases.rancher.com/install-docker/19.03.sh | sh
	curl -sfl https://get.k3s.io | sh -s - --docker
SHELL
	
Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vbguest.auto_update = true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vbguest.no_remote = false
    config.vm.define "eroddS", primary: true do |server|
      server.vm.network "private_network", ip: server_ip
      server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      server.vm.hostname = "eroddS"
      server.vm.provider "virtualbox" do |srv|
        srv.name = "eroddS"
        srv.memory = 4096
        srv.cpus = 4
        srv.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        srv.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	      srv.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
      end
    server.vm.provision :shell, inline: server_script
    server.vm.provision :shell, path: "./scripts/deploy.sh"
    end
    config.vm.provision "shell", inline: <<-SHELL
	    sudo systemctl disable firewalld --now
      sudo dnf install net-tools -y
	    echo 'alias k="k3s kubectl"' >> /home/vagrant/.bashrc
	    sudo yum update -y
	    sudo yum install ufw -y
	    yes | sudo ufw enable
	    sudo ufw allow 6443/tcp
	    sudo ufw allow 443/tcp
    SHELL
  end
  
